trigger:
  - master

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Installing Node.js'

  - script: |
      npm install -g nx
      npm ci
    displayName: 'Installing dependencies'

  - script: |
      nx lint frontend
    displayName: 'Linting'

  - script: |
      nx test frontend
    displayName: 'Unit testing'

  - script: |
      nx build frontend --configuration=production
    displayName: 'Building'

  # - script: |
  #   displayName: 'Deploying'
