trigger:
  - master

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Installing Node.js'

  - script: |
      npm ci
    displayName: 'Installing dependencies'

  - script: |
      npx nx lint frontend
    displayName: 'Linting'

  - script: |
      npx nx test frontend
    displayName: 'Unit testing'

  - script: |
      npx nx build frontend --configuration=production
    displayName: 'Building'

  # - script: |
  #   displayName: 'Deploying'
