trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - powershell: |
      $sourceBranch = "$(System.PullRequest.SourceBranch)"

      if($sourceBranch -ne "refs/heads/develop")
      {
        exit 1
      }
    displayName: 'Validating source branch'
