trigger: none

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Installing Node.js'

  - script: |
      npm ci
    displayName: 'Installing dependencies'

  - script: |
      nx lint api
    displayName: 'Linting backend'

  - script: |
      nx test api
    displayName: 'Unit testing backend'

  - script: |
      nx lint frontend
    displayName: 'Linting frontend'

  - script: |
      nx lint shared-components
    displayName: 'Linting shared components'

  - script: |
      nx test frontend
    displayName: 'Unit testing frontend'
